### PR TITLE
build: upgrade GradleVersion to 7.6

### PR DESCRIPTION
**Pull request by majadlymhmd**
## What this PR changes/adds
upgrades the gradle version to 7.6.

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Relates https://github.com/eclipse-edc/Connector/issues/2290

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Comment by paullatzelsperger** [comment]
@majadlymhmd there is an awful log of checkstyle errors. can you rebase onto main and check on you local machine what's going on there?

**Comment by majadlymhmd** [comment]
@paullatzelsperger i checked it, it's because the ApiClient class cannot be imported and found in the client directory !

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger i checked it, it's because the ApiClient class cannot be imported and found in the client directory !

`ApiClient` is generated code. However, the problem was an incomplete checkstyle configuration, in particular the `suppressions.xml` file was not correctly configured. Please apply the path in [this gist](https://gist.github.com/paullatzelsperger/d54472abf7d3c962bcd2e1aea732ed14), that should do the trick.

**Comment by paullatzelsperger** [comment]
@majadlymhmd one more thing: it seems like in `resources/checkstyle-config`, line 31 should be: 
```diff
@@ -29,8 +29,7 @@
   </module>
   <!-- https://checkstyle.org/config_filters.html#SuppressionFilter -->
   <module name="SuppressionFilter">
-    <property name="file" value="${org.checkstyle.google.suppressionfilter.config}"
-              default="${config_loc}/checkstyle-suppressions.xml"/>
+    <property name="file" value="${config_loc}/checkstyle-suppressions.xml"/>
     <property name="optional" value="false"/>
   </module>
```
that should fix the remaining build errors.

**Pull request merged**
